# Generated by Django 5.2.8 on 2025-12-13 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='User location', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market.serviceoffer'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Rating from 1 to 5'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='User who wrote the review', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market.servicerequest'),
        ),
        migrations.AddField(
            model_name='review',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='User being reviewed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='location',
            field=models.CharField(blank=True, help_text='Location name (city, district, etc.)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(blank=True, help_text='Location name (city, district, etc.)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='Review comment'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('offer__isnull', False)), fields=('reviewer', 'offer'), name='unique_offer_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('service_request__isnull', False)), fields=('reviewer', 'service_request'), name='unique_request_review'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='listing_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rated_user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rater',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score',
        ),
    ]
