# Generated by Django 5.2.8 on 2025-12-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Semantic tags from Wikidata'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Semantic tags from Wikidata'),
        ),
    ]
