# Generated by Django 5.2.8 on 2025-12-06 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_interactionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactionrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='timetransaction',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='timetransaction',
            name='status',
        ),
        migrations.AddField(
            model_name='interactionrequest',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interactionrequest',
            name='is_completed_by_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interactionrequest',
            name='is_confirmed_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetransaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interactionrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Optional initial message'),
        ),
        migrations.AlterField(
            model_name='interactionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='duration',
            field=models.IntegerField(default=1, help_text='Duration in hours (Integer)'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='duration',
            field=models.IntegerField(default=1, help_text='Requested duration in hours (Integer)'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='market.interactionrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=3, help_text='Kullanıcının sahip olduğu saat miktarı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
