# Generated by Django 5.2.8 on 2025-12-13 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_review_unique_together_profile_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interactionrequest',
            name='date_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_dates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interactionrequest',
            name='deleted_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interactionrequest',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interactionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('date_proposed', 'Date Proposed'), ('declined', 'Declined'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('negotiating', 'Negotiating')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'New Message'), ('date_proposed', 'Date Proposed'), ('date_rejected', 'Date Rejected'), ('date_accepted', 'Date Accepted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('interaction_accepted', 'Interaction Accepted'), ('interaction_declined', 'Interaction Declined')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='market.interactionrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
