# Generated by Django 5.2.8 on 2025-12-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_chatmessage_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
