# Generated by Django 5.2.8 on 2025-12-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_chatmessage_deleted_by_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffer',
            name='address',
            field=models.TextField(blank=True, help_text='Address text', null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='address',
            field=models.TextField(blank=True, help_text='Address text', null=True),
        ),
    ]
