# Generated by Django 5.2.8 on 2025-12-08 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_interactionrequest_date_proposed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionrequest',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='market.servicerequest'),
        ),
        migrations.AlterField(
            model_name='interactionrequest',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='market.serviceoffer'),
        ),
    ]
