# Generated by Django 5.2.8 on 2025-12-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_servicecompletionconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='content',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='ServiceCompletionConfirmation',
        ),
    ]
