# Generated by Django 5.2.8 on 2025-12-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_interactionrequest_service_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='address',
            field=models.TextField(blank=True, help_text='Address text'),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='address',
            field=models.TextField(blank=True, help_text='Address text'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
    ]
