# Generated by Django 5.2.8 on 2025-12-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_serviceoffer_address_serviceoffer_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='image',
            field=models.ImageField(blank=True, help_text='Listing image', null=True, upload_to='listings/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='image',
            field=models.ImageField(blank=True, help_text='Listing image', null=True, upload_to='listings/'),
        ),
    ]
