# Generated by Django 5.2.8 on 2025-12-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_chatmessage_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoffer',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='serviceoffer',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='serviceoffer',
            name='scheduled_date',
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('group_request', 'Group Request'), ('event', 'Event'), ('help', 'Help')], default='general', max_length=20),
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
