# Generated by Django 5.2.8 on 2025-12-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_remove_serviceoffer_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffer',
            name='capacity',
            field=models.IntegerField(default=1, help_text='Maximum number of participants (spots available)'),
        ),
    ]
