# Generated by Django 5.2.8 on 2025-12-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_serviceoffer_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumcomment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('group_request', 'Group Request'), ('event', 'Event'), ('help', 'Help')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceoffer',
            name='capacity',
            field=models.IntegerField(default=1, help_text='Number of spots available for this offer'),
        ),
    ]
