# Generated by Django 5.2.8 on 2025-12-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_remove_forumcomment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
