# Generated by Django 5.2.8 on 2025-11-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0.0, help_text='Kullanıcının toplam zaman bakiyesi (saat cinsinden).'),
        ),
    ]
