"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# === Base directory ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === Load environment variables ===
dotenv_path = BASE_DIR / ".env"
load_dotenv(str(dotenv_path))

# === Security ===
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-q-xl_9&p7ye53v$)2x*lle-l2p%5e7#6t(6-i)94b%&^-#gs_+")

# === DEBUG ===
# Production ortamında debug kapalı olmalı
# Render'da DEBUG ortam değişkenini 'False' olarak ayarla
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

# === ALLOWED_HOSTS ===
# Hem localhost hem de Render'dan gelen tüm domainleri kabul et
ALLOWED_HOSTS = ['*']  # Production'da daha spesifik yapılabilir: ['localhost', '127.0.0.1', '.onrender.com']

# === Installed apps ===
INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',  # CORS için

    # Local apps
    'accounts',
    'market',
]

# === Middleware ===
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files için (SecurityMiddleware'den sonra olmalı)
    'corsheaders.middleware.CorsMiddleware',  # CORS için (CommonMiddleware'den önce olmalı)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

# === Templates ===
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "core" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'market.context_processors.notification_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# === Database ===
# Render'da DATABASE_URL ortam değişkeni varsa onu kullan, yoksa sqlite3 kullan
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Production (Render) - DATABASE_URL kullan
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Development (Local) - SQLite kullan
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# === Password validation ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# === Internationalization ===
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# === Static files ===
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise static files storage (production için)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# === Media files ===
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# === Default primary key field type ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === Custom user & DRF settings ===
AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# === CORS Settings ===
# Hata ayıklamak için şimdilik tüm originlere izin ver
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# === Session Settings ===
# Oturum süresini 2 hafta yap (saniye cinsinden: 14 gün * 24 saat * 60 dakika * 60 saniye)
SESSION_COOKIE_AGE = 1209600

# Kullanıcı sitede her tıkladığında oturum süresini sıfırla (aktifken atılmaz)
SESSION_SAVE_EVERY_REQUEST = True

# Tarayıcıyı kapatsa bile oturum açık kalsın
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
